site_name: nomad-gallery
site_description: A mkdocs-based GitHub Pages site for showcasing NOMAD features, examples, and use cases.
site_author: Joseph Rudzinski

repo_url: https://github.com/FAIRmat-NFDI/nomad-gallery
edit_uri: ""

nav:
  - Home: index.md
  - Submissions: submissions.md
  # - Tutorial: tutorial/tutorial.md
  # - How-to guides:
  #     - Install this Plugin: how_to/install_this_plugin.md
  #     - Use this Plugin: how_to/use_this_plugin.md
  #     - Contribute to this plugin: how_to/contribute_to_this_plugin.md
  #     - Contribute to the documentation: how_to/contribute_to_the_documentation.md
  # - Explanation: explanation/explanation.md
  # - Reference: reference/references.md
plugins:
  - search
  - include-markdown:
      include_dir: docs
  - macros
theme:
  name: material
  palette:
    primary: "#2A4CDF"
    accent: "#008A67"
  font:
    text: "Titillium Web"
  logo: assets/nomad-plugin-logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - content.tabs.link
  custom_dir: docs/theme
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: True
  - pymdownx.arithmatex:
      generic: true
  - mkdocs-click
  - pymdownx.extra
extra:
  generator: false
  homepage: https://nomad-lab.eu
use_directory_urls: false
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascript.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
